Move help pages to confluence

diff --git a/opi/scripts/libera-help b/opi/scripts/libera-help
--- a/opi/scripts/libera-help
+++ b/opi/scripts/libera-help
@@ -1,3 +1,20 @@
-#!/bin/sh
-URL="http://www.cs.diamond.ac.uk/cgi-bin/wiki.cgi/Libera_opi_$1"
-firefox -new-window "$URL" &
+#!/bin/bash
+# Helper for launching Libera help pages
+
+HERE="$(dirname "$0")"
+
+TABLE="$HERE"/help_table
+
+# Searches for given key in $TABLE, assigns result to URL, fails if not found
+search_for()
+{
+    URL="$(sed -n "/^$1  */{s///;p;}" "$TABLE")"  &&
+    [[ -n "$URL" ]]
+}
+
+# Try for requested page, then try fallback page if necessary
+if search_for "$1"  ||  search_for '\*'; then
+    firefox -new-window "$URL" &
+else
+    echo >&2 "Unable to find help page for $1 or default help page"
+fi
