Libera: Implement initial timestamp synchronisation.
git-svn-id: svn+ssh://serv0002.cs.diamond.ac.uk/home/subversion/repos/controls/diamond/trunk/ioc/Libera@4365 e099a375-04f9-0310-9d5f-a741eaff62e1

diff --git a/install/epics b/install/epics
--- a/install/epics
+++ b/install/epics
@@ -57,10 +57,16 @@ case "$1" in
         [ -e /var/run/ioc.pid ] && kill "$(cat /var/run/ioc.pid)"
         evaluate_retval
 
-        # Try a rather more rigorous stop if the kill above failed.
-        sleep 0.5
-        [ -e /var/run/ioc.pid ] && kill -9 "$(cat /var/run/ioc.pid)"  &&
-        echo >&2 'IOC killed forcibly!'
+        # Try a rather more rigorous stop if the kill above failed.  Give the
+        # process a couple of seconds to die.
+        for ((i = 0; i < 20; i ++)); do
+            [ -e /var/run/ioc.pid ]  ||  break
+            sleep 0.1
+        done
+        if [ -e /var/run/ioc.pid ]; then
+            kill -9 "$(cat /var/run/ioc.pid)"  &&
+            echo >&2 'IOC killed forcibly!'
+        fi
         
         # Make sure that the ioc.pid file doesn't stay around, otherwise if
         # the ioc dies without removing its pid file we can never restart
