Libera:  * Step to version 1.46.2.0 for test deployment to machine.  * Tweak to lmtd for transition between control modes.  * Remove MAXADC:IIR from SA display as it's currently worthless.  * Fix rather major bug in initialisation order: it's rather important to    initialise all the synchronisation stuff before using it!  * Tweaks to the startup script for 2.6 distribution compatibility.  * Add little script for probing clock tuning control.
git-svn-id: svn+ssh://serv0002.cs.diamond.ac.uk/home/subversion/repos/controls/diamond/trunk/ioc/Libera@12472 e099a375-04f9-0310-9d5f-a741eaff62e1

diff --git a/install/epics b/install/epics
--- a/install/epics
+++ b/install/epics
@@ -31,10 +31,40 @@
 # This file should be placed in /etc/init.d/epics
 
 # Pick up the epics ioc definitions: this tells us where to find the IOC.
-. /etc/sysconfig/epics_ioc
+# There are two possible locations, depending on which version of Libera we're
+# running.
+if [ -d /etc/sysconfig ]; then
+    . /etc/sysconfig/epics_ioc
+else
+    . /etc/default/epics_ioc
+fi
 
-# We use the standard print_status and evaluate_retval functions.
-. /etc/init.d/functions
+
+# The following functions were defined in /etc/init.d/functions on Libera on
+# linux 2.4, but don't seem to have equivalents in the more recent
+# distribution, so we define what we need here.
+evaluate_retval()
+{
+    if [ $? = 0 ]; then
+        print_status success
+    else
+        print_status failure
+    fi
+}
+
+: "${COLUMNS:=80}"      # Ensure COLUMNS is set
+print_status()
+{
+    echo -n $'\033['"$((COLUMNS-10))G"
+    echo -n [
+    case "$1" in
+        success)    echo -n $'\033[1;32m  OK  ' ;;
+        failure)    echo -n $'\033[1;31mFAILED' ;;
+    esac
+    echo -n $'\033[0;39m'
+    echo ]
+}
+
 
 # Sensible defaults
 IOC_LOG="${IOC_LOG:-/var/log/ioc}"
