Libera:  Take over control of libera startup script (now renamed to libera-driver) and start and stop the clock PLL daemon there.  The runioc and installation scripts are updated accordingly.
git-svn-id: svn+ssh://serv0002.cs.diamond.ac.uk/home/subversion/repos/controls/diamond/trunk/ioc/Libera@16308 e099a375-04f9-0310-9d5f-a741eaff62e1

diff --git a/install/libera-install-ioc b/install/libera-install-ioc
--- a/install/libera-install-ioc
+++ b/install/libera-install-ioc
@@ -34,6 +34,9 @@
 # IOC: testing (installed on the remote file system) or final (copied to the
 # local file system).
 
+# Abort on first failure
+set -e
+
 function Error()
 {
     echo >&2 "$@"
@@ -120,6 +123,13 @@ if [ -e /var/run/ioc.pid ]; then
     fi
 fi
 
+# Similarly ensure that none of the libera drivers are running.
+if ! [ -x /etc/init.d/libera-driver ]; then
+    [ -e /var/run/clockPll.pid ]  &&  kill $(cat /var/run/clockPll.pid)
+    /etc/init.d/libera stop
+    mv /etc/init.d/libera /etc/init.d/old-libera
+fi
+
 
 # If final installation selected then copy over all the run-time files and
 # update the configuration file to point to them.
@@ -129,13 +139,13 @@ if [ $TARGET == final ]; then
     STATE_DIR=/opt/state
 
     # Ensure the state directory exists (but don't interfere with it!)
-    mkdir -p "$STATE_DIR"  &&
+    mkdir -p "$STATE_DIR"  
 
     # Copy over all the runtime files.  First make sure the target directory
     # is fresh.
-    rm -rf "$IOC_TARGET"  &&
-    umask 22  &&
-    mkdir -p "$IOC_TARGET"  &&
+    rm -rf "$IOC_TARGET"  
+    umask 22  
+    mkdir -p "$IOC_TARGET"  
     for dir in bin dbd db; do
         cp -r "$SOURCE/$dir" "$IOC_TARGET"
     done
@@ -146,7 +156,7 @@ else
     # Check that the parent directory contains the right files!
     [ "$IOC_TARGET" = "$SOURCE" ] ||
         Error "Inconsistent test installation environment"
-fi  &&
+fi  
 
 # Now install the epics_ioc file.
 (
@@ -161,31 +171,33 @@ fi  &&
         s/^'"$LOCATION"'_(IOC_)/\1/
         /^IOC_/! d
         ' "$SOURCE"/install/CONFIG
+    # If libera autostart is configured then add the appropriate entry
+    [ $AUTOSTART = libera ]  &&
+        echo 'SERVER_BOOT=/etc/init.d/epics'
 ) > $CONFIGDIR/epics_ioc
 
-# Copy the startup script
-cp -f "$SOURCE"/install/epics /etc/init.d  &&
+# Copy the startup scripts
+cp -f "$SOURCE"/install/libera-driver /etc/init.d  
+cp -f "$SOURCE"/install/epics /etc/init.d  
+
 
 # Configure autostart as required.  First clear out any existing autostart
 # method, then install the chosen one.  Either we start epics separately from
 # libera, or we invite the libera script to start/stop us at the same time.
-rm -f /etc/rc3.d/S900epics /etc/rc6.d/K100epics  &&
-rm -f $CONFIGDIR/libera-server  &&
-rm -f /etc/init.d/libera-server  &&
-case $AUTOSTART in
-    none) ;;    # Already done!
-    epics)
-        ln -sf ../init.d/epics /etc/rc3.d/S900epics  &&
-        ln -sf ../init.d/epics /etc/rc6.d/K100epics
-        ;;
-    libera)
-        echo SERVER_BOOT=yes > $CONFIGDIR/libera-server  &&
-        ln -sf epics /etc/init.d/libera-server  &&
-        ln -sf ../init.d/epics /etc/rc6.d/K100libera
-        ;;
-    *)  Error 'Oops!'
-esac
+rm -f /etc/rc3.d/S900epics /etc/rc6.d/K100epics  
+rm -f $CONFIGDIR/libera-server  
+rm -f /etc/init.d/libera-server  
+rm -f /etc/rc3.d/S800libera /etc/rc6.d/K100libera  
+
+ln -fs ../init.d/libera-driver /etc/rc3.d/S800libera-driver  
+ln -fs ../init.d/libera-driver /etc/rc6.d/K100libera-driver  
+
+if [ $AUTOSTART = epics ]; then
+    ln -sf ../init.d/epics /etc/rc3.d/S900epics  
+    ln -sf ../init.d/epics /etc/rc6.d/K100epics
+fi
 
 if ((STARTNOW)); then
-    /etc/init.d/epics start
+    /etc/init.d/libera-driver start
+    [ $AUTOSTART = libera ]  ||  /etc/init.d/epics start
 fi
