Libera: Version 1.46.4.2  * Add support for new ADC overflow detection algorithm.  At this point we    also add code to check for a new DLS EXTENSION bit in the ITECH FEATURE    register together with a bit in the CUSTOMER FEATURE register (called the    DLS FEATURE register in the code).       Documentation of this feature remains to be written, and an agreement    with iTech on the use of the DLS EXTENSION bit still needs to be ratified.    At the moment this is slightly speculative.       One important backwards incompatibility is that the SA MAXADC register    is also no longer read unless this bit is set.  * Update cagetall and caputall to use cothread and add TS liberas to allbpms    list.  * Tweak the coding and comments of filter-header.py, but filter is unchanged.  * Make the libera-install-ioc script slightly more clever and cope with the    rootfs mounted read only.
git-svn-id: svn+ssh://serv0002.cs.diamond.ac.uk/home/subversion/repos/controls/diamond/trunk/ioc/Libera@25459 e099a375-04f9-0310-9d5f-a741eaff62e1

diff --git a/install/libera-install-ioc b/install/libera-install-ioc
--- a/install/libera-install-ioc
+++ b/install/libera-install-ioc
@@ -80,7 +80,8 @@ LOCATIONS="$(cat "$SOURCE"/install/locations)"
 TARGET=none
 AUTOSTART=0
 STARTNOW=0
-while getopts 'ftlash' option; do
+REMOUNT_RW=0
+while getopts 'ftlaswh' option; do
     case "$option" in
     f)  TARGET=final ;;
     t)  TARGET=test ;;
@@ -88,6 +89,7 @@ while getopts 'ftlash' option; do
     l)  echo 'The -l option is obsolete: use -a'
         AUTOSTART=1 ;;
     s)  STARTNOW=1 ;;
+    w)  REMOUNT_RW=1 ;;
     h)  echo -n 'Usage: libera-install-ioc <options>'
         if [ -n "$LOCATIONS" ]; then echo ' <location>'; else echo; fi
         cat <<'EOF'
@@ -96,6 +98,7 @@ where <options> includes
     -t  Testing install: don't copy files, use from configured location
     -a  Enable autostart via /etc/init.d/libera-driver script.
     -s  Start IOC after installation
+    -w  Remount ro rootfs rw if necessary
 EOF
         [ -n "$LOCATIONS" ]  &&  cat <<EOF
 and <location> is a two character location code used to configure location
@@ -130,6 +133,18 @@ fi
 (($# != 0))  &&
     Error 'Invalid arguments: try -h for help'
 
+
+# Check whether we can write to the filesystem.
+if cat /proc/mounts | grep -q ' / [^ ]* ro '; then
+    # Root is mounted read only.  Bail unless remount requested.
+    if ((REMOUNT_RW)); then
+        mount -o rw,remount /  ||
+            Error 'Unable to remount rootfs for writing'
+        trap 'mount -o ro,remount /' EXIT
+    else
+        Error 'Rootfs is mounted read-only.  Try -w option'
+    fi
+fi
 
 
 # Make sure the libera driver isn't running: we need to stop everything, as
