Libera: Take charge of installation of /opt/lib, /opt/bin
The entire /opt directory is now managed by the Libera install.
Scripts are added for installing FPGAs and for managing the location
of Libera: can now run /opt/bin/configure-location to switch between
storage ring and booster.

The location string for the booster has been changed from BR to BO to
avoid confusion, especially with BR for Brilliance.

Also change computation of FPGA_VERSION string to take extended DLS
versioning into account.

git-svn-id: svn+ssh://serv0002.cs.diamond.ac.uk/home/subversion/repos/controls/diamond/trunk/ioc/Libera@62921 e099a375-04f9-0310-9d5f-a741eaff62e1

diff --git a/scripts/epics-functions b/scripts/epics-functions
--- a/scripts/epics-functions
+++ b/scripts/epics-functions
@@ -142,3 +142,23 @@ probe_libera()
         echo -n PHOTON
     fi
 }
+
+
+# This function ensures that we can write to the filesytem, or fails if
+# remounting is not enabled.  Called as
+#
+#   ensure_root_rw <enable-remount>
+#
+ensure_root_rw()
+{
+    if grep -qE ' / [^ ]* ro(,| )' /proc/mounts; then
+        # Root is mounted read only.  Bail unless remount requested.
+        if $1; then
+            mount -o remount,rw /  ||
+                Error 'Unable to remount rootfs for writing'
+            trap 'mount -o remount,ro /' EXIT
+        else
+            Error 'Rootfs is mounted read-only.  Try -w option'
+        fi
+    fi
+}
